name: Build for Linux

on:
  push:
  workflow_dispatch:

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Install deps
        run: |
          sudo apt-get update -y
          sudo apt install -y software-properties-common
          sudo apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
          sudo apt install -y unzip nodejs autoconf automake build-essential clang cmake execstack fakeroot git libc-ares-dev libctemplate-dev libcurl4-openssl-dev libglib2.0-dev libicu-dev libsasl2-dev libsasl2-modules libsasl2-modules-gssapi-mit libsecret-1-dev libssl-dev libnss3 libnss3-dev libtidy-dev libtool libxext-dev libxkbfile-dev libxml2-dev libxtst-dev rpm uuid-dev xvfb

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache NodeJS modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./app/node_modules
          key: ubuntu-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('app/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: DEBUG=electron-packager npm run build

      - name: Upload Deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mailspring-Linux-Deb
          path: app/dist/mailspring-*.deb

      - name: Upload RPM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mailspring-Linux-RPM
          path: app/dist/mailspring-*.rpm

      - name: Upload Main Directory Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mailspring-Linux-x64
          path: app/dist/mailspring-linux-x64