name: Build for Windows

on:
  push:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache NodeJS modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./app/node_modules
          key: windows-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('app/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: List build output files
        run: |
          Get-ChildItem app\dist\ -Recurse

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mailspring-Windows-Exe
          path: app/dist/Mailspring-win32-x64/Mailspring.exe