name: Build for macOS

on:
  push:
  workflow_dispatch:

jobs:
  build-macos:
    strategy:
      matrix:
        # Confusingly, macos-13 is intel and macos-latest is ARM
        os: [macos-13, macos-latest]
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Cache NodeJS modules
        uses: actions/cache@v4
        with:
          path: |
            ./node_modules
            ./app/node_modules
          key: ${{ matrix.os }}-${{ runner.arch }}-deps-${{ hashFiles('yarn.lock') }}-${{ hashFiles('app/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: DEBUG=electron-packager,electron-osx-sign,electron-notarize* npm run build

      - name: Rename artifacts
        if: matrix.os == 'macos-latest'
        run: |
          mv app/dist/Mailspring.zip app/dist/Mailspring-AppleSilicon.zip

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Mailspring-${{ matrix.os }}
          path: |
            app/dist/Mailspring*.zip
