name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Zip all directories in artifacts
        run: |
          find ./artifacts -mindepth 1 -maxdepth 1 -type d | while read dir; do
            # 只压缩不是 .zip 结尾的目录
            if [ -d "$dir" ] && [[ ! "$dir" =~ \.zip$ ]]; then
              zipname="${dir}.zip"
              echo "Zipping $dir to $zipname"
              cd "$dir"
              zip -r "../$(basename "$dir").zip" ./*
              cd - > /dev/null
            fi
          done

      - name: List all files to upload
        run: find ./artifacts -type f

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for file in $(find ./artifacts -type f); do
            echo "Uploading $file"
            gh release upload "${{ github.ref_name }}" "$file"
          done 